In [3]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[]
#l= [11,22,33,44]

for i,j in zip(l1,l2):
    l.append(i+j)

print(l)
    

[11, 22, 33, 44]


In [5]:
l=[i+j for i,j in zip(l1,l2)]

In [7]:
l

[11, 22, 33, 44]

In [9]:
l1+l2

[10, 20, 30, 40, 1, 2, 3, 4]

In [11]:
import numpy as np

In [15]:
arr1= np.array(l1)

In [17]:
type(arr1)

numpy.ndarray

In [19]:
arr2= np.array(l2)

In [21]:
arr2

array([1, 2, 3, 4])

In [23]:
print('arr1: ', arr1)

arr1:  [10 20 30 40]


In [25]:
print('arr2: ', arr2)

arr2:  [1 2 3 4]


In [27]:
arr1+arr2

array([11, 22, 33, 44])

In [29]:
l1*l2

TypeError: can't multiply sequence by non-int of type 'list'

In [31]:
arr1*arr2

array([ 10,  40,  90, 160])

In [33]:
print(arr1+arr2)

[11 22 33 44]


In [35]:
print(arr1/arr2)

[10. 10. 10. 10.]


In [37]:
print(arr1%arr2)

[0 0 0 0]


In [39]:
print(arr1 - arr2)

[ 9 18 27 36]


**Use Case2**

In [46]:
import time
start= time.time()
l1= list(range(1,1000000))
l2= list(range(1,1000000))
mul=[i*j for i,j in zip(l1,l2)]
end= time.time()
print(end- start)

0.20082569122314453


In [52]:
import time
import numpy as np
start= time.time()
arr1= np.arange(1,100000000)
arr2= np.arange(1,100000000)
mul= arr1*arr2
end= time.time()
print(end- start)

0.8254637718200684


In [54]:
import time
start=time.time()
l1=list(range(1,100000000))
l2=list(range(1,000000000))
mul=[i*j for i,j in zip(l1,l2)]
end=time.time()
print("total time taken is:",(end-start))

total time taken is: 2.7919692993164062
